### ISSUE TITLE
Usage example in Readme has syntax error

### ISSUE THREAD

**Issue by mywristbands** [dkershner6/shopify-application-proxy-verification#22]
In the `Usage` section of the Readme, it contains a syntax error. The line:
`if ((verifyAppProxyHmac(req.query), process.env.SHOPIFY_SECRET)) {`
should be:
`if (verifyAppProxyHmac(req.query, process.env.SHOPIFY_SECRET)) {`

**Comment by mywristbands** [comment]
I'd also recommend changing `process.env.SHOPIFY_SECRET` to `process.env.SHOPIFY_API_SECRET`, since that's what it is named by default.

**Comment by dkershner6** [comment]
Changes have been made, thank you for pointing this out.

**Comment by mywristbands** [comment]
Thanks for the fix, but it looks like you accidentally introduced another error! You need to remove the extra `if`.

**Comment by dkershner6** [comment]
You can see how deeply I rely on Typescript and ESLint.  That...has also been fixed.
